[phases.setup]
nixPkgs = ["nodejs_20", "python312", "python312Packages.numpy", "python312Packages.pandas"]

[phases.install]
cmds = [
  "npm install",
  "npm --prefix backend install",
  "npm --prefix frontend install"
]

[phases.build]
cmds = ["CI=false npm run build"]

[start]
cmd = "bash start.sh"
